# Generated by Django 6.0.7 on 2026-07-19 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('investment', 'Investment'), ('real_estate', 'Real Estate'), ('gold', 'Gold'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='cash', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
