# Generated by Django 6.0.7 on 2026-07-19 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('current', 'Current Asset'), ('fixed', 'Fixed Asset')], default='current', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('fd', 'Fixed Deposit (FD)'), ('rd', 'Recurring Deposit (RD)'), ('investment', 'Investment'), ('receivable', 'Receivable / Money Due'), ('real_estate', 'Real Estate'), ('gold', 'Gold'), ('business', 'Business Equity'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('liability_type', models.CharField(choices=[('bill', 'Unpaid Bill'), ('rent', 'Rent Due'), ('tax', 'Tax Due'), ('personal_debt', 'Personal Debt'), ('other', 'Other Liability')], default='bill', max_length=20)),
                ('liability_class', models.CharField(choices=[('short_term', 'Short-term Liability'), ('long_term', 'Long-term Liability')], default='short_term', max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Liabilities',
                'ordering': ['-created_at'],
            },
        ),
    ]
