# Generated by Django 6.0.7 on 2026-07-20 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notif_type', models.CharField(choices=[('emi_upcoming', 'EMI Upcoming'), ('emi_overdue', 'EMI Overdue'), ('payment_received', 'Payment Received'), ('loan_closed', 'Loan Closed'), ('info', 'Info')], db_index=True, default='info', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'notif_type'], name='notificatio_user_id_9e5454_idx')],
            },
        ),
    ]
