# Generated by Django 6.0.7 on 2026-07-23 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTimelineEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('loan_created', 'Loan Created'), ('loan_updated', 'Loan Updated'), ('loan_closed', 'Loan Closed'), ('payment_added', 'Payment Added'), ('receipt_uploaded', 'Receipt Uploaded'), ('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted'), ('plan_changed', 'Plan Changed'), ('feature_enabled', 'Feature Flag Enabled'), ('feature_disabled', 'Feature Flag Disabled'), ('ai_insight', 'AI Insight Generated'), ('automation_triggered', 'Automation Rule Triggered'), ('report_generated', 'Report Generated'), ('profile_updated', 'Profile Updated'), ('login', 'User Login')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_timeline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_timeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('calculation_context', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.aiconversation')),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAISettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('monthly_query_limit', models.PositiveIntegerField(default=100)),
                ('queries_used_this_month', models.PositiveIntegerField(default=0)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('response_style', models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed'), ('conversational', 'Conversational')], default='conversational', max_length=20)),
                ('privacy_mode', models.BooleanField(default=False, help_text='Anonymize data in AI responses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ai_settings',
            },
        ),
    ]
