# Generated by Django 6.0.7 on 2026-07-23 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('loan_created', 'Loan Created'), ('loan_updated', 'Loan Updated'), ('loan_deleted', 'Loan Deleted'), ('payment_recorded', 'Payment Recorded'), ('receipt_uploaded', 'Receipt Uploaded'), ('proof_generated', 'Proof Generated'), ('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_rejected', 'Invitation Rejected'), ('role_changed', 'Role Changed'), ('feature_flag_toggled', 'Feature Flag Toggled'), ('plan_changed', 'Subscription Plan Changed'), ('setting_updated', 'Setting Updated')], db_index=True, max_length=50)),
                ('target_resource', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'created_at'], name='audit_logs_organiz_af0d8d_idx'), models.Index(fields=['workspace_id', 'created_at'], name='audit_logs_workspa_bba528_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx')],
            },
        ),
    ]
