# Generated by Django 6.0.7 on 2026-07-14 06:18

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'HDFC Home Loan'", max_length=200)),
                ('loan_type', models.CharField(choices=[('home', 'Home Loan'), ('personal', 'Personal Loan'), ('vehicle', 'Vehicle Loan'), ('education', 'Education Loan'), ('business', 'Business Loan'), ('credit_card', 'Credit Card'), ('other', 'Other')], db_index=True, default='personal', max_length=20)),
                ('lender_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(blank=True, help_text='Loan account number from lender — stored encrypted in production', max_length=100)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate as a percentage, e.g. 8.50 for 8.5%', max_digits=5)),
                ('monthly_emi', models.DecimalField(decimal_places=2, help_text='Equated Monthly Installment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('next_emi_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted'), ('on_hold', 'On Hold')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
    ]
