# Generated by Django 6.0.7 on 2026-07-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower_wallet',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='loan',
            name='escrow_contract_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_escrow',
            field=models.BooleanField(default=False, help_text='If true, this loan is managed via smart contract on Monad'),
        ),
        migrations.AddField(
            model_name='loan',
            name='lender_wallet',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
