# Generated by Django 6.0.7 on 2026-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_borrower_wallet_loan_escrow_contract_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='agreement_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='contract_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Counterparty Signature'), ('active', 'Active / Binding'), ('settled', 'Settled / Complete')], default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='counterparty_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loan',
            name='counterparty_name',
            field=models.CharField(blank=True, help_text='Name of friend/family/business partner', max_length=200),
        ),
        migrations.AddField(
            model_name='loan',
            name='counterparty_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_p2p_agreement',
            field=models.BooleanField(default=False, help_text='If true, this is a peer-to-peer debt agreement with a formal digital promissory note'),
        ),
    ]
