# Generated by Django 6.0.7 on 2026-07-23 09:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('emi_due_in_days', 'EMI Due in N Days'), ('loan_overdue', 'Loan Becomes Overdue'), ('budget_exceeded', 'Budget Exceeds Limit'), ('investment_drop', 'Investment Drops by N%'), ('card_utilization_high', 'Credit Card Utilization Exceeds N%'), ('payment_due', 'Payment Due Date Approaching')], max_length=50)),
                ('condition_value', models.JSONField(default=dict, help_text="e.g. {'days': 3} or {'threshold': 70}")),
                ('action_type', models.CharField(choices=[('send_notification', 'Send In-App Notification'), ('send_email', 'Send Email'), ('show_warning', 'Show Dashboard Warning'), ('recommend_payment', 'Recommend Payment Action')], max_length=50)),
                ('action_config', models.JSONField(default=dict, help_text="e.g. {'message': 'Your EMI is due soon!'}")),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation_rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=20)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('context_data', models.JSONField(default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='automation.automationrule')),
            ],
            options={
                'db_table': 'automation_execution_logs',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
