# Generated by Django 6.0.7 on 2026-07-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='assigned_workspaces',
            field=models.ManyToManyField(blank=True, related_name='assigned_members', to='tenants.workspace'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='features_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_custom_branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='savings_badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='workspace_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20),
        ),
    ]
