# Generated by Django 6.0.7 on 2026-07-14 06:18

import apps.payments.models
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text="Machine-readable action name, e.g. 'user.registered', 'payment.created'", max_length=100)),
                ('resource_type', models.CharField(blank=True, help_text="The type of resource affected, e.g. 'Loan', 'Payment'", max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='UUID of the affected resource', max_length=36)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured context for the event')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('cheque', 'Cheque'), ('auto_debit', 'Auto Debit'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference / UTR / transaction ID', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='confirmed', max_length=20)),
                ('principal_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of EMI that reduces principal', max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of EMI that covers interest', max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(help_text='The original receipt document (PDF/image)', upload_to=apps.payments.models._receipt_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('document_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the receipt document. This is what gets anchored on blockchain.', max_length=64, unique=True)),
                ('hash_algorithm', models.CharField(default='sha256', help_text='Algorithm used to generate document_hash', max_length=20)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
