# Generated by Django 6.0.7 on 2026-07-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='blockchain_anchored_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of blockchain confirmation', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='blockchain_block_number',
            field=models.PositiveBigIntegerField(blank=True, help_text='Blockchain block number', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='blockchain_network',
            field=models.CharField(default='monad-testnet', help_text='Target blockchain network', max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='blockchain_proof_id',
            field=models.CharField(blank=True, help_text='UUID Proof ID stored on blockchain', max_length=36),
        ),
        migrations.AddField(
            model_name='receipt',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66),
        ),
        migrations.AddField(
            model_name='receipt',
            name='blockchain_wallet_address',
            field=models.CharField(blank=True, help_text='Wallet address that signed/stored the proof', max_length=42),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_blockchain_verified',
            field=models.BooleanField(default=False, help_text='Status indicating whether proof is successfully stored on-chain'),
        ),
    ]
