# Generated by Django 6.0.7 on 2026-07-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_receipt_blockchain_anchored_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_user_id_d685f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_action_391715_idx',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
