# Generated by Django 6.0.7 on 2026-07-20 09:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('cheque', 'Cheque'), ('auto_debit', 'Auto Debit'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Reference/UTR number', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit_cards.creditcard')),
            ],
            options={
                'verbose_name': 'Credit Card Payment',
                'verbose_name_plural': 'Credit Card Payments',
                'db_table': 'credit_card_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
